'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicioTaxi
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Articulos", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Articulos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoCentralField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuntosField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoCentral() As String
            Get
                Return Me.CodigoCentralField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoCentralField, value) <> true) Then
                    Me.CodigoCentralField = value
                    Me.RaisePropertyChanged("CodigoCentral")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puntos() As Decimal
            Get
                Return Me.PuntosField
            End Get
            Set
                If (Me.PuntosField.Equals(value) <> true) Then
                    Me.PuntosField = value
                    Me.RaisePropertyChanged("Puntos")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="InfoError", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InfoError
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private detalleErroresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private mensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private resultadoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property detalleErrores() As String
            Get
                Return Me.detalleErroresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.detalleErroresField, value) <> true) Then
                    Me.detalleErroresField = value
                    Me.RaisePropertyChanged("detalleErrores")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property mensajeError() As String
            Get
                Return Me.mensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.mensajeErrorField, value) <> true) Then
                    Me.mensajeErrorField = value
                    Me.RaisePropertyChanged("mensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                If (Me.resultadoField.Equals(value) <> true) Then
                    Me.resultadoField = value
                    Me.RaisePropertyChanged("resultado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Ventas", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Ventas
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoletaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaHoraField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteTotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LineasField() As ServicioTaxi.LineasVentas
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MatriculaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuntosTotalField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenciaPuntoCompraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenciaTaxistaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Boleta() As String
            Get
                Return Me.BoletaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BoletaField, value) <> true) Then
                    Me.BoletaField = value
                    Me.RaisePropertyChanged("Boleta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaHora() As Date
            Get
                Return Me.FechaHoraField
            End Get
            Set
                If (Me.FechaHoraField.Equals(value) <> true) Then
                    Me.FechaHoraField = value
                    Me.RaisePropertyChanged("FechaHora")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImporteTotal() As Double
            Get
                Return Me.ImporteTotalField
            End Get
            Set
                If (Me.ImporteTotalField.Equals(value) <> true) Then
                    Me.ImporteTotalField = value
                    Me.RaisePropertyChanged("ImporteTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Lineas() As ServicioTaxi.LineasVentas()
            Get
                Return Me.LineasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LineasField, value) <> true) Then
                    Me.LineasField = value
                    Me.RaisePropertyChanged("Lineas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Matricula() As String
            Get
                Return Me.MatriculaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatriculaField, value) <> true) Then
                    Me.MatriculaField = value
                    Me.RaisePropertyChanged("Matricula")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PuntosTotal() As Double
            Get
                Return Me.PuntosTotalField
            End Get
            Set
                If (Me.PuntosTotalField.Equals(value) <> true) Then
                    Me.PuntosTotalField = value
                    Me.RaisePropertyChanged("PuntosTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReferenciaPuntoCompra() As String
            Get
                Return Me.ReferenciaPuntoCompraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenciaPuntoCompraField, value) <> true) Then
                    Me.ReferenciaPuntoCompraField = value
                    Me.RaisePropertyChanged("ReferenciaPuntoCompra")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReferenciaTaxista() As String
            Get
                Return Me.ReferenciaTaxistaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenciaTaxistaField, value) <> true) Then
                    Me.ReferenciaTaxistaField = value
                    Me.RaisePropertyChanged("ReferenciaTaxista")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LineasVentas", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio.Entidades"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LineasVentas
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoArticuloCentralField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImporteField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LineaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuntosField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PuntosTotalField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VentaField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoArticuloCentral() As String
            Get
                Return Me.CodigoArticuloCentralField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoArticuloCentralField, value) <> true) Then
                    Me.CodigoArticuloCentralField = value
                    Me.RaisePropertyChanged("CodigoArticuloCentral")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Importe() As Decimal
            Get
                Return Me.ImporteField
            End Get
            Set
                If (Me.ImporteField.Equals(value) <> true) Then
                    Me.ImporteField = value
                    Me.RaisePropertyChanged("Importe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Linea() As Integer
            Get
                Return Me.LineaField
            End Get
            Set
                If (Me.LineaField.Equals(value) <> true) Then
                    Me.LineaField = value
                    Me.RaisePropertyChanged("Linea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Puntos() As Decimal
            Get
                Return Me.PuntosField
            End Get
            Set
                If (Me.PuntosField.Equals(value) <> true) Then
                    Me.PuntosField = value
                    Me.RaisePropertyChanged("Puntos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PuntosTotal() As Decimal
            Get
                Return Me.PuntosTotalField
            End Get
            Set
                If (Me.PuntosTotalField.Equals(value) <> true) Then
                    Me.PuntosTotalField = value
                    Me.RaisePropertyChanged("PuntosTotal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Venta() As Integer
            Get
                Return Me.VentaField
            End Get
            Set
                If (Me.VentaField.Equals(value) <> true) Then
                    Me.VentaField = value
                    Me.RaisePropertyChanged("Venta")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioTaxi.IServicioTaxi")>  _
    Public Interface IServicioTaxi
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioTaxi/obtenerArticulos", ReplyAction:="http://tempuri.org/IServicioTaxi/obtenerArticulosResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServicioTaxi.InfoError), Action:="http://tempuri.org/IServicioTaxi/obtenerArticulosInfoErrorFault", Name:="InfoError", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio")>  _
        Function obtenerArticulos(ByVal refrenciaPuntoCompra As String, ByVal clave As String) As ServicioTaxi.Articulos()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioTaxi/enviarVentas", ReplyAction:="http://tempuri.org/IServicioTaxi/enviarVentasResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServicioTaxi.InfoError), Action:="http://tempuri.org/IServicioTaxi/enviarVentasInfoErrorFault", Name:="InfoError", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio")>  _
        Function enviarVentas(ByVal refrenciaPuntoCompra As String, ByVal clave As String, ByVal ventas() As ServicioTaxi.Ventas) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServicioTaxi/enviarVenta", ReplyAction:="http://tempuri.org/IServicioTaxi/enviarVentaResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServicioTaxi.InfoError), Action:="http://tempuri.org/IServicioTaxi/enviarVentaInfoErrorFault", Name:="InfoError", [Namespace]:="http://schemas.datacontract.org/2004/07/AMSystem.GestionTaxi.Servicio")>  _
        Function enviarVenta(ByVal PuntoCompra As String, ByVal clave As String, ByVal Factura As String, ByVal Placa As String, ByVal Taxista As String, ByVal Fecha As String, ByVal Hora As String, ByVal Articulo As String, ByVal Monto As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServicioTaxiChannel
        Inherits ServicioTaxi.IServicioTaxi, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioTaxiClient
        Inherits System.ServiceModel.ClientBase(Of ServicioTaxi.IServicioTaxi)
        Implements ServicioTaxi.IServicioTaxi
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function obtenerArticulos(ByVal refrenciaPuntoCompra As String, ByVal clave As String) As ServicioTaxi.Articulos() Implements ServicioTaxi.IServicioTaxi.obtenerArticulos
            Return MyBase.Channel.obtenerArticulos(refrenciaPuntoCompra, clave)
        End Function
        
        Public Function enviarVentas(ByVal refrenciaPuntoCompra As String, ByVal clave As String, ByVal ventas() As ServicioTaxi.Ventas) As Boolean Implements ServicioTaxi.IServicioTaxi.enviarVentas
            Return MyBase.Channel.enviarVentas(refrenciaPuntoCompra, clave, ventas)
        End Function
        
        Public Function enviarVenta(ByVal PuntoCompra As String, ByVal clave As String, ByVal Factura As String, ByVal Placa As String, ByVal Taxista As String, ByVal Fecha As String, ByVal Hora As String, ByVal Articulo As String, ByVal Monto As String) As Boolean Implements ServicioTaxi.IServicioTaxi.enviarVenta
            Return MyBase.Channel.enviarVenta(PuntoCompra, clave, Factura, Placa, Taxista, Fecha, Hora, Articulo, Monto)
        End Function
    End Class
End Namespace
